server:
  port: 8084

spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

queue:
  batch-size: 50
  process-interval-ms: 3000
  token-ttl-seconds: 300
